# Generated by Django 6.0.2 on 2026-02-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookConsignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(max_length=255)),
                ('Cargo_type', models.EmailField(max_length=254)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('no_of_pieces', models.IntegerField()),
                ('description', models.TextField()),
                ('origine_country', models.CharField(max_length=255)),
                ('city_or_port_origine', models.CharField(max_length=255)),
                ('pickup_address', models.TextField()),
                ('destination_country', models.CharField(max_length=255)),
                ('city_or_port_destination', models.CharField(max_length=255)),
                ('deluvery_address', models.TextField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
