# Generated by Django 6.0.2 on 2026-02-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookconsignment',
            name='Cargo_type',
            field=models.CharField(max_length=255),
        ),
    ]
